title: Minty
email: kabirgoel.kg@gmail.com
description: >
  A refreshingly simple way to work.
baseurl: "/minty"
url: "//kabirgoel.com"
twitter_username: notkabir
github_username: kbrgl

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
 - jekyll-coffeescript